run:
  concurrency: 0
  timeout: 10m
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

linters-settings:
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true
  lll:
    tab-width: 2
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

linters:
  enable:
    - lll
    - bodyclose
    - goconst
    - goimports
    - gosec
    - revive
    - dupl

issues:
  exclude-use-default: true
  #  exclude:
  #    - declaration of "(err|ctx)" shadows declaration at
  include:
    - EXC0012 # comment checking enabled
    - EXC0014 # comment checking enabled
  exclude-dirs-use-default: true
  exclude-dirs:
    - bin
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  max-same-issues: 0
  new: true
  fix: true
